<?
$root = "../";
$title = "AXA Chair";
include $root."layout/header.php";
?>

<b>AXA Chair</b>

<p>
AXA chairs are funded by the <a href="https://www.axa-research.org/" target="_blank">AXA Research Fund</a>, which supports fundamental research to advance our understanding of risk. 
The AXA Chair scheme started in 2008 and it dedicates up to eight million euros to support four to eight Chairs every year. 
They are individual fellowships, and the one at EURECOM is going to support my research activities for seven years (2016-2023). 
The AXA Chair selection process is not based on the project only, but also on timeliness, vision, credibility of both the proposal and the candidate, institution and fit within EURECOM&#39;s strategy. 
</p>

<p>
<b>The project: Novel Computational Approaches to Risk Modeling</b>
</p>

<p>
The AXA Chair project deals with one simple question: How do you go from data to decisions? Today, we have access to so much data generated by a variety of sensors, but we are facing difficulties in using these data in a sensible way. 
Machine Learning and Statistics offer the main tools to help making sense of data, and novel techniques in this domain will be used and developed throughout this project. 
Quantification of risk and decision-making require accurate quantification of uncertainty, which is a major challenge in many areas of sciences involving complex phenomena like finance, environmental and life sciences. 
In order to accurately quantify uncertainty, we employ flexible and accurate tools offered by probabilistic nonparametric statistical models. 
However, today&#39;s diversity and abundance of data make it difficult to use these models in practice. 
The goal of this project is to propose new ways to better manage the interface between computational and statistical models - which in turn will help get accurate quantification of the confidence in the predictions based on observed data.
</p>

<p>
The idea behind the project is that it is possible to carry out accurate quantification of uncertainty relying exclusively on approximate, and therefore cheaper, computations. 
Using nonparametric models is difficult and generally computationally intractable due to the complexity of the systems and the amount of data. 
Although computers are becoming increasingly more powerful, exact computations remain serial, too long, too expensive and sometimes even impossible to carry out. 
The way approximate computations will be designed in this project will be able to reduce computing time significantly. 
The exploitation of parallel and distributed computing on large-scale computing facilities - for which EURECOM has a huge expertise - will be key to achieve this. 
We will thus be able to develop new inference tools and statistical models that will make accurate quantification of uncertainty possible.
</p>

<p>
Part of the focus of the project will be on life and environmental applications that require quantification of risk.  We will then use mostly life sciences data (e.g., neuroimaging and genomics) and environmental data for our models. This project will help tackle the explosion of large scale and diverse data in life and environmental sciences. This is already a huge challenge today, and it will be even more difficult to deal with in the future. In the mid-term, we will develop practical and scalable algorithms that learn from data and accurately quantify their uncertainty on predictions. On a longer term, we will be able to improve on current approaches for risk estimation: they will be timely and more accurate. These approaches can have major implications in the development of medical treatment strategies or environmental policies for example. Is some seismic activity going to trigger a tsunami for which it is worth warning the population or not? Is a person showing signs of a systemic disease, like Parkinson, actually going develop the disease or not? We hope that the results of our project will make it easier to answer these questions.
</p>

<?
include $root."layout/footer.php";
?>
